#include "document.h"
#include "paragraph.h"

int main() {

	Document document1("New component JYScrollPaneMap which is pretty useful    for large scrollpane views");
	document1.setTargetLength(50);
	document1.format();
	std::cout << document1.render() << std::endl;

	Document document2("\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sapien tortor, iaculis quis velit et, vulputate pretium ante. Integer at magna porttitor urna rutrum consectetur. Vestibulum eget felis tempor, tincidunt magna sed, porta est. Suspendisse ullamcorper justo interdum tristique commodo. Suspendisse eu ligula leo. Cras dapibus dapibus consequat. Aliquam id ipsum quis ipsum luctus pellentesque sed nec elit. Curabitur interdum tortor et rutrum mattis. Integer molestie vel magna vitae aliquam. Suspendisse dignissim non felis eget venenatis. Etiam tempus sodales malesuada. Phasellus sed vehicula mi, a maximus ex.\n\n\tInteger rutrum diam et diam dictum, eget finibus nibh vehicula. Etiam rutrum id sapien blandit tempus. In hac habitasse platea dictumst. Morbi finibus risus ut enim egestas, sed tempor mi feugiat. Quisque non turpis non ante placerat maximus. Proin porttitor ex eget neque pulvinar tincidunt. Curabitur quis augue a nulla consequat feugiat. Quisque enim metus, imperdiet sit amet suscipit auctor, vulputate eget ex.\n\n\tIn sit amet libero massa. Nunc tellus nunc, sagittis eget risus ut, malesuada gravida mi. In finibus tellus et ex congue ultrices sed nec eros. Nulla facilisi. Proin mattis lorem quis nisi pretium finibus. Morbi tempor tellus vel nisi dapibus, et porttitor nibh semper. Quisque bibendum ex eget risus hendrerit gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer imperdiet eros sed neque dignissim rutrum. Pellentesque eget posuere est, at consectetur tellus. Donec diam nisl, luctus et nibh nec, tempor condimentum eros. Integer venenatis dolor quam, eget condimentum erat mollis id. Aenean cursus lorem in faucibus pretium. Morbi eget tristique diam.\n\n\tFusce rhoncus justo nisl, ut faucibus est rutrum a. Vivamus nisi velit, imperdiet sit amet accumsan id, eleifend sed mauris. Aenean vulputate mauris at dui vulputate, vitae luctus turpis vulputate. Vestibulum massa sem, fringilla a dignissim vitae, pulvinar at elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras consectetur a magna et varius. Integer sed metus facilisis, porta metus ac, aliquet magna. Ut auctor nibh non massa aliquet dignissim.\n\n\tNullam placerat, orci quis euismod ullamcorper, magna orci congue orci, laoreet faucibus mi elit eget lorem. Donec sit amet malesuada quam, vitae tincidunt dolor. Mauris dignissim eleifend nisl sed ornare. Nullam sollicitudin dolor sed tortor euismod consequat. Vestibulum in suscipit sem, eget rutrum libero. Suspendisse ac nisi ac diam sollicitudin maximus. Morbi ultrices consequat accumsan. Nunc mattis tortor et varius convallis.");
	document2.setTargetLength(100);
	document2.format();
	std::cout << document2.render() << std::endl;
}